force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Actual__c</fullName>
    <label>Project Total Administrative Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Expenses__c</fullName>
    <inlineHelpText>Administrative expenses specific to the project</inlineHelpText>
    <label>Project Total Administrative Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Other_Fund__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Other_Fund__c</fullName>
    <label>Project Total Administrative Other Fund</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Administrative expenses</inlineHelpText>
    <label>Project Total Administrative Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Actual__c</fullName>
    <label>Project Total Direct Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Expenses__c</fullName>
    <inlineHelpText>Direct expenses specifically used for the project</inlineHelpText>
    <label>Project Total Direct Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Other_Fund_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Other_Fund_Source__c</fullName>
    <label>Project Total Direct Other Fund Source</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Direct expenses</inlineHelpText>
    <label>Project Total Direct Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Actual__c</fullName>
    <label>Project Total Personnel Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Expenses__c</fullName>
    <inlineHelpText>Direct personnel expenses specific to the project</inlineHelpText>
    <label>Project Total Personnel Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Other_Fund_Sourc__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Other_Fund_Sourc__c</fullName>
    <label>Project Total Personnel Other Fund Sourc</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Personnel</inlineHelpText>
    <label>Project Total Personnel Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/Grant_Budget__c.object-meta.xml
<CustomObject>
    <label>Grant Budget</label>
    <nameField>
        <displayFormat>GB-{0000}</displayFormat>
        <label>Grant Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Budget__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Amount_Applied_from_Sentara_Grant__c.field-meta.xml
<CustomField>
    <fullName>Amount_Applied_from_Sentara_Grant__c</fullName>
    <label>Amount Applied from Sentara Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Grant Budgets</relationshipLabel>
    <relationshipName>Grant_Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Budget_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Line_Item__c</fullName>
    <label>Budget Line Item</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Expense_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Category__c</fullName>
    <label>Expense Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Direct Expenses</fullName>
            </value>
            <value>
                <fullName>Administrative Expenses %28not to exceed 15%25 of grant request%29</fullName>
            </value>
            <value>
                <fullName>Direct - Project Personnel Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Line_funding_source__c.field-meta.xml
<CustomField>
    <fullName>Line_funding_source__c</fullName>
    <description>Funding source for line item</description>
    <label>Line Funding Source</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Project_Budget__c.field-meta.xml
<CustomField>
    <fullName>Project_Budget__c</fullName>
    <label>Project Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/Grant_Other_Funders__c.object-meta.xml
<CustomObject>
    <description>This object is used to identify other organizations that also funded the program that the applicant has asked Sentara to fund.</description>
    <label>Grant Other Funders</label>
    <nameField>
        <displayFormat>GOF-{0000}</displayFormat>
        <label>Grant Other Funders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Other Funders</relationshipLabel>
    <relationshipName>Other_Funders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funder_Name__c.field-meta.xml
<CustomField>
    <fullName>Funder_Name__c</fullName>
    <label>Funder Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funding_From__c.field-meta.xml
<CustomField>
    <fullName>Funding_From__c</fullName>
    <label>Funding From</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sentara Corporate</fullName>
            </value>
            <value>
                <fullName>Sentara Hospital</fullName>
            </value>
            <value>
                <fullName>Optima Health</fullName>
            </value>
            <value>
                <fullName>Virginia Premier</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funding_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Funding_Project_Name__c</fullName>
    <description>Project Name funded by other sources</description>
    <label>Funding Project Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funding_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Start_Date__c</fullName>
    <description>Start date of the other funding source</description>
    <label>Funding Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Prior_Year_Fund_Source__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year_Fund_Source__c</fullName>
    <label>Prior Year Fund Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationPdfController.cls
public with sharing class ApplicationPdfController {
    public Application__c application { get; set; }
    public String recordId { get; set; }

    public ApplicationPdfController() {
        string appId = System.currentPageReference().getParameters().get('id');
        recordId = appId;
        application = getApplicationDetails(recordId);
    }


    public static Application__c getApplicationDetails(String appId){
        return [SELECT Project_Total_Direct_Expenses__c,Project_Total_Direct_Requested__c,
         Project_Total_Direct_Other_Fund_Source__c,Project_Total_Direct_Actual__c,Project_Total_Administrative_Expenses__c,
         Project_Total_Administrative_Requested__c,Project_Total_Administrative_Other_Fund__c,Project_Total_Administrative_Actual__c,
         Project_Total_Personnel_Expenses__c,Project_Total_Personnel_Requested__c,Project_Total_Personnel_Other_Fund_Sourc__c,
         Project_Total_Personnel_Actual__c, ( SELECT Id,Expense_Category__c,Budget_Line_Item__c,Project_Budget__c,Amount_Applied_from_Sentara_Grant__c,
         Line_funding_source__c,Actual_Amount__c FROM Grant_Budgets__r ), ( SELECT Id,Prior_Year_Fund_Source__c,Funder_Name__c,
         Funding_From__c,Funding_Project_Name__c,Funding_Amount__c,Request_Status__c,Funding_Start_Date__c FROM Other_Funders__r )
         FROM Application__c WHERE Id =: appId];
     }

}