force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Budget__c/Grant_Budget__c.object-meta.xml
<CustomObject>
    <label>Grant Budget</label>
    <nameField>
        <displayFormat>GB-{0000}</displayFormat>
        <label>Grant Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Budget__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Amount_Applied_from_Sentara_Grant__c.field-meta.xml
<CustomField>
    <fullName>Amount_Applied_from_Sentara_Grant__c</fullName>
    <label>Amount Applied from Sentara Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Grant Budgets</relationshipLabel>
    <relationshipName>Grant_Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Budget_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Line_Item__c</fullName>
    <label>Budget Line Item</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Expense_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Category__c</fullName>
    <label>Expense Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Direct Expenses</fullName>
            </value>
            <value>
                <fullName>Administrative Expenses %28not to exceed 15%25 of grant request%29</fullName>
            </value>
            <value>
                <fullName>Direct - Project Personnel Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Line_funding_source__c.field-meta.xml
<CustomField>
    <fullName>Line_funding_source__c</fullName>
    <description>Funding source for line item</description>
    <label>Line Funding Source</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Project_Budget__c.field-meta.xml
<CustomField>
    <fullName>Project_Budget__c</fullName>
    <label>Project Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/rowIndex__c.field-meta.xml
<CustomField>
    <fullName>rowIndex__c</fullName>
    <label>rowIndex</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/grandBudgetHelper.cls
public with sharing class grandBudgetHelper {

    public static ObjectWrappersClasses.concatObjWrapper getDBData(String appId,String expenseCategory){
        Decimal totalPercentage;
        List<ObjectWrappersClasses.grandtFundersWrapperCalss> dgbwList = new List<ObjectWrappersClasses.grandtFundersWrapperCalss>();
        List<Grant_Budget__c> gbList = [SELECT Id,Expense_Category__c,Budget_Line_Item__c,Project_Budget__c,Amount_Applied_from_Sentara_Grant__c,
        Line_funding_source__c,Actual_Amount__c,Application__c,rowIndex__c FROM Grant_Budget__c 
        WHERE Application__c =: appId AND Expense_Category__c =:expenseCategory Order By rowIndex__c ASC];
        if(!gbList.isEmpty()){
            for(Grant_Budget__c gb : gbList){
                ObjectWrappersClasses.grandtFundersWrapperCalss dgbw = new ObjectWrappersClasses.grandtFundersWrapperCalss();
                dgbw.recId = gb.Id;
                dgbw.Id = gb.rowIndex__c;
                dgbw.colexpenseCategory = gb.Expense_Category__c;
                dgbw.expenseCategory = gb.Budget_Line_Item__c;
                dgbw.totalBudget = String.valueOf(gb.Project_Budget__c);
                dgbw.requestedFromSentara = String.valueOf(gb.Amount_Applied_from_Sentara_Grant__c);
                dgbw.otherFundingSources = String.valueOf(gb.Line_funding_source__c);
                dgbw.actualGrantExpenses = String.valueOf(gb.Actual_Amount__c);
                dgbw.rowIndex = gb.rowIndex__c;
                Decimal diffValue;
                if(gb.Project_Budget__c != null && gb.Project_Budget__c != 0){
                    diffValue = gb.Project_Budget__c - gb.Amount_Applied_from_Sentara_Grant__c;
                }
                dgbw.diff = String.ValueOf(diffValue);
                Decimal persentageValue;
                if(gb.Project_Budget__c != null && gb.Project_Budget__c != 0){
                    persentageValue = (gb.Amount_Applied_from_Sentara_Grant__c / gb.Project_Budget__c) * 100;
                }
                if(totalPercentage != null && persentageValue != null){
                    totalPercentage = totalPercentage + persentageValue;
                }
                dgbw.percentage = String.ValueOf((persentageValue));
                dgbwList.add(dgbw);
            }
        }
        Application__c appDetails = applicationHelper.getApplicationDetails(appId);
        ObjectWrappersClasses.concatObjWrapper cow = new ObjectWrappersClasses.concatObjWrapper();
        cow.objWrapList = dgbwList;
        cow.applicationDetails = appDetails;
        cow.totalPercentage = totalPercentage;
        return cow;
    }

    public static List<Grant_Budget__c> getGrandBudgets(String parRecId){

        List<Grant_Budget__c> gbList = [SELECT Id, Status__c FROM Grant_Budget__c 
                                        WHERE Application__c =:parRecId AND Status__c =: 'Draft'];

        return gbList;
    }
}