force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documents__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/Grant_Budget__c.object-meta.xml
<CustomObject>
    <label>Grant Budget</label>
    <nameField>
        <displayFormat>GB-{0000}</displayFormat>
        <label>Grant Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Budget__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Grant Budgets</relationshipLabel>
    <relationshipName>Grant_Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Expense_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Category__c</fullName>
    <label>Expense Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Direct Expenses</fullName>
            </value>
            <value>
                <fullName>Administrative Expenses %28not to exceed 15%25 of grant request%29</fullName>
            </value>
            <value>
                <fullName>Direct - Project Personnel Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/Grant_Other_Funders__c.object-meta.xml
<CustomObject>
    <description>This object is used to identify other organizations that also funded the program that the applicant has asked Sentara to fund.</description>
    <label>Grant Other Funders</label>
    <nameField>
        <displayFormat>GOF-{0000}</displayFormat>
        <label>Grant Other Funders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Other Funders</relationshipLabel>
    <relationshipName>Other_Funders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funder_Name__c.field-meta.xml
<CustomField>
    <fullName>Funder_Name__c</fullName>
    <label>Funder Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funding_From__c.field-meta.xml
<CustomField>
    <fullName>Funding_From__c</fullName>
    <label>Funding From</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sentara Corporate</fullName>
            </value>
            <value>
                <fullName>Sentara Hospital</fullName>
            </value>
            <value>
                <fullName>Optima Health</fullName>
            </value>
            <value>
                <fullName>Virginia Premier</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Funding_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Funding_Project_Name__c</fullName>
    <description>Project Name funded by other sources</description>
    <label>Funding Project Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Prior_Year_Fund_Source__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year_Fund_Source__c</fullName>
    <label>Prior Year Fund Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant_Other_Funders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OtherFundingResourceCtrlTest.cls
@isTest
public class OtherFundingResourceCtrlTest {
    public static final String userName = 'test.portal@example.com';
    @TestSetup
    public static void setup() {
        User externalUser = TestDataFactory.getGuestUser();
        externalUser.LastName = 'testUserExternal';
        update externalUser;
        System.runAs(externalUser){
            Account site = TestDataFactory.getSiteAccount();
            
            Contact newContact = TestDataFactory.getContact('Bob', 'Tester');
            newContact.AccountId = site.Id;
            newContact.Email = 'testuser@test.com';
            insert newContact;
            
            Test.startTest();
            String ProfileName = 'Customer Community Login User';
            TestDataFactory.getPortalUser(ProfileName, userName, newContact.Id);
            Test.stopTest();
            
            User PortalUser = [SELECT Id,UserName from User where UserName = : userName];
            System.assertEquals(PortalUser.UserName, userName);
            
            Application__c app = new Application__c();
            app.Account__c = site.Id;
            insert app;
            
            Grant_Other_Funders__c gof = new Grant_Other_Funders__c();
            gof.Application__c = app.Id;
            gof.Funding_From__c = 'Sentara Corporate';
            gof.Status__c = 'Draft';
            gof.Funding_Project_Name__c = 'Test';
            gof.Prior_Year_Fund_Source__c = 'Sentara Artifacts';
            gof.Funder_Name__c = 'Test';
            gof.Funding_Amount__c = 50.00;
            gof.Request_Status__c = 'Submitted';
            insert gof;
            
            Grant_Other_Funders__c gofa = new Grant_Other_Funders__c();
            gofa.Application__c = app.Id;
            gofa.Funding_From__c = 'Sentara Corporate';
            gofa.Status__c = 'Draft';
            gofa.Funding_Project_Name__c = 'Test';
            gofa.Prior_Year_Fund_Source__c = 'Sentara Artifacts';
            gofa.Funder_Name__c = 'Test';
            gofa.Funding_Amount__c = 50.00;
            gofa.Request_Status__c = 'Pending';
            insert gofa;
            
            Grant_Budget__c gb = new Grant_Budget__c();
            gb.Application__c = app.Id;
            gb.Status__c = 'Draft';
            gb.Expense_Category__c = 'Direct - Project Personnel Expenses';
            insert gb;
            
        }
    }
    @isTest
    public static void createOtherFundingResourceTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        List<ObjectWrappersClasses.otherGrandtFundersWrapperCalss> objectList = new List<ObjectWrappersClasses.otherGrandtFundersWrapperCalss>();
        ObjectWrappersClasses.otherGrandtFundersWrapperCalss wrapObject = new ObjectWrappersClasses.otherGrandtFundersWrapperCalss();
        Test.startTest();
        wrapObject.amountAwarded = '50.00';
        wrapObject.disableOtherFunders = true;
        wrapObject.fundingForm = 'Sentara Corporate';
        wrapObject.otherFunders = 'Sentara Corporate';
        wrapObject.fundingSource = 'Sentara Artifacts';
        wrapObject.isOtherFunderForm = true;
        wrapObject.nameOftheProj = 'Test';
        wrapObject.rowIndex = '0';
        objectList.add(wrapObject);
        Map<String,String> retMap = OtherFundingResourceCtrl.createOtherFundingResource(JSON.serialize(objectList),app.Id,'0');
        List<ObjectWrappersClasses.otherGrandtFundersWrapperCalss> reList = OtherFundingResourceCtrl.getOtherFundingResouceRecords(app.Id);
        Test.stopTest();
    }
    @isTest
    public static void createDocumentTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        User userDetail = [SELECT Id from User WHERE LastName = 'testUserExternal'];
        System.runAs(userDetail){
            Test.startTest();
            ContentVersion content=new ContentVersion(); 
            content.Title='Header_Picture1'; 
            content.PathOnClient='/' + content.Title + '.jpg'; 
            Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
            content.VersionData=bodyBlob; 
            insert content;
            Id contentDocId = [select contentdocumentId from contentversion where Id =: content.Id].contentdocumentId;
            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=app.Id;
            contentlink.contentdocumentId=contentDocId;
            contentlink.ShareType = 'I';
            contentlink.Visibility = 'AllUsers'; 
            insert contentlink;
            Documents__c docretun = OtherFundingResourceCtrl.createDocument('Program/Project Budget Template',app.Id);
            String retStr = OtherFundingResourceCtrl.getDocWithType('Program/Project Budget Template',app.Id);
            String detStr = OtherFundingResourceCtrl.deleteSingleAttachment(contentDocId);
            Test.stopTest();
        }
    }
    
    @isTest
    public static void sendEmailTest(){
        User userDetail = [SELECT Id from User WHERE LastName = 'testUserExternal'];
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        System.runAs(userDetail){
            Test.startTest();
            String str = OtherFundingResourceCtrl.sendEmail(app.Id);
            Test.stopTest();
        }
    }
    
    @isTest
    public static void getAllBudgetsTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        Test.startTest();
        String Strrtn = OtherFundingResourceCtrl.getAllBudgets(app.Id, 'Direct - Project Personnel Expenses');
        Test.stopTest();
    }
    
    @isTest
    public static void deleteRowTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        Grant_Budget__c gb = [SELECT Id FROM Grant_Budget__c LIMIT 1];
        Test.startTest();
        String Strrtn = OtherFundingResourceCtrl.deleteRow(gb.Id,app.Id, 'Direct - Project Personnel Expenses');
        Test.stopTest();
    }
    
    @isTest
    public static void deleteOFRRowTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        Grant_Other_Funders__c gof = [SELECT Id FROM Grant_Other_Funders__c WHERE Request_Status__c = 'Pending' LIMIT 1];
        Test.startTest();
        String Strrtn = OtherFundingResourceCtrl.deleteOFRRow(gof.Id,app.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getDataUpsertTest(){
        Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        List<ObjectWrappersClasses.grandtFundersWrapperCalss> gfwList = new List<ObjectWrappersClasses.grandtFundersWrapperCalss>();
        ObjectWrappersClasses.grandtFundersWrapperCalss gfwObject = new ObjectWrappersClasses.grandtFundersWrapperCalss();
        gfwObject.colexpenseCategory = 'Direct - Project Personnel Expenses';
        gfwObject.expenseCategory = 'Personla';
        gfwObject.totalBudget = '10.00';
        gfwObject.requestedFromSentara = '10.00';
        gfwObject.otherFundingSources = '10.00';
        gfwObject.actualGrantExpenses = '10.00';
        gfwObject.rowIndex = '1';
        gfwList.add(gfwObject);
        Test.startTest();
        Map<String,String> retMap = OtherFundingResourceCtrl.getDataUpsert(JSON.serialize(gfwList),app.Id,'1');
        Test.stopTest();
    }
    
    @isTest
    public static void updateStatusForGBAndOGBTest(){
         Application__c app = [SELECT Id FROM Application__c LIMIT 1];
        Map<String,Map<String,String>> concatMap = new Map<String,Map<String,String>>();
        Map<String,String> mergeMap = new Map<String,String>();
        mergeMap.put('totalcolBudget','10.00');
        mergeMap.put('totalcolrequestedFromSentara','10.00');
        mergeMap.put('totalcolotherFundingSources','10.00');
        mergeMap.put('totalcolactualGrantExpenses','10.00');
        concatMap.put('totalotherDirectExpenses',mergeMap);
        concatMap.put('totaladministrativeExpenses',mergeMap);
        concatMap.put('totalPersonnelExpenses',mergeMap);
        Test.startTest();
        String returnStr = OtherFundingResourceCtrl.updateStatusForGBAndOGB(app.Id, true, concatMap);
        Test.stopTest();
            
    }
}