force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Actual__c</fullName>
    <label>Project Total Administrative Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Expenses__c</fullName>
    <inlineHelpText>Administrative expenses specific to the project</inlineHelpText>
    <label>Project Total Administrative Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Other_Fund__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Other_Fund__c</fullName>
    <label>Project Total Administrative Other Fund</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Administrative_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Administrative_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Administrative expenses</inlineHelpText>
    <label>Project Total Administrative Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Actual__c</fullName>
    <label>Project Total Direct Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Expenses__c</fullName>
    <inlineHelpText>Direct expenses specifically used for the project</inlineHelpText>
    <label>Project Total Direct Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Other_Fund_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Other_Fund_Source__c</fullName>
    <label>Project Total Direct Other Fund Source</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Direct_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Direct_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Direct expenses</inlineHelpText>
    <label>Project Total Direct Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Actual__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Actual__c</fullName>
    <label>Project Total Personnel Actual</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Expenses__c</fullName>
    <inlineHelpText>Direct personnel expenses specific to the project</inlineHelpText>
    <label>Project Total Personnel Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Other_Fund_Sourc__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Other_Fund_Sourc__c</fullName>
    <label>Project Total Personnel Other Fund Sourc</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Total_Personnel_Requested__c.field-meta.xml
<CustomField>
    <fullName>Project_Total_Personnel_Requested__c</fullName>
    <inlineHelpText>Project amount requested from Sentara related to Personnel</inlineHelpText>
    <label>Project Total Personnel Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/applicationHelper.cls
public with sharing class applicationHelper {
   public static Boolean updateApplicationRecord(Map<String,Map<String,String>> wrapOnject, String appId){
        Boolean isUpdated = false;
        List<Application__c> applicationList = new List<Application__c>();
        Set<Application__c> applicationSet = new Set<Application__c>();
        Application__c app = new Application__c();
        app.Id = appId;
        for(String key : wrapOnject.keySet()){
            if(key.equals('totalotherDirectExpenses')){
                app.Project_Total_Direct_Expenses__c = Decimal.ValueOf(wrapOnject.get('totalotherDirectExpenses').get('totalcolBudget'));
                app.Project_Total_Direct_Requested__c = Decimal.ValueOf(wrapOnject.get('totalotherDirectExpenses').get('totalcolrequestedFromSentara'));
                app.Project_Total_Direct_Other_Fund_Source__c = Decimal.ValueOf(wrapOnject.get('totalotherDirectExpenses').get('totalcolotherFundingSources'));
                app.Project_Total_Direct_Actual__c = Decimal.ValueOf(wrapOnject.get('totalotherDirectExpenses').get('totalcolactualGrantExpenses'));
                applicationList.add(app);
            }else if(key.equals('totaladministrativeExpenses')){
                app.Project_Total_Administrative_Expenses__c = Decimal.ValueOf(wrapOnject.get('totaladministrativeExpenses').get('totalcolBudget'));
                app.Project_Total_Administrative_Requested__c = Decimal.ValueOf(wrapOnject.get('totaladministrativeExpenses').get('totalcolrequestedFromSentara'));
                app.Project_Total_Administrative_Other_Fund__c = Decimal.ValueOf(wrapOnject.get('totaladministrativeExpenses').get('totalcolotherFundingSources'));
                app.Project_Total_Administrative_Actual__c = Decimal.ValueOf(wrapOnject.get('totaladministrativeExpenses').get('totalcolactualGrantExpenses'));
                applicationList.add(app);
            }else if(key.equals('totalPersonnelExpenses')){
                app.Project_Total_Personnel_Expenses__c = Decimal.ValueOf(wrapOnject.get('totalPersonnelExpenses').get('totalcolBudget'));
                app.Project_Total_Personnel_Requested__c = Decimal.ValueOf(wrapOnject.get('totalPersonnelExpenses').get('totalcolrequestedFromSentara'));
                app.Project_Total_Personnel_Other_Fund_Sourc__c = Decimal.ValueOf(wrapOnject.get('totalPersonnelExpenses').get('totalcolotherFundingSources'));
                app.Project_Total_Personnel_Actual__c = Decimal.ValueOf(wrapOnject.get('totalPersonnelExpenses').get('totalcolactualGrantExpenses'));
                applicationList.add(app);
            }
        }
        applicationSet.addAll(applicationList);
        if(!applicationSet.isEmpty()){
            List<Application__c> appList = new List<Application__c>(applicationSet);
            update appList;
            isUpdated = true;
        }
        return isUpdated;
    }

    public static Application__c getApplicationDetails(String appId){
       return [SELECT Project_Total_Direct_Expenses__c,Project_Total_Direct_Requested__c,
                Project_Total_Direct_Other_Fund_Source__c,Project_Total_Direct_Actual__c,Project_Total_Administrative_Expenses__c,
                Project_Total_Administrative_Requested__c,Project_Total_Administrative_Other_Fund__c,Project_Total_Administrative_Actual__c,
                Project_Total_Personnel_Expenses__c,Project_Total_Personnel_Requested__c,Project_Total_Personnel_Other_Fund_Sourc__c,Project_Total_Personnel_Actual__c
                FROM Application__c WHERE Id =: appId];
    }
}