force-app/main/default/objects/Account/fields/propper_message__c.field-meta.xml
<CustomField>
    <fullName>propper_message__c</fullName>
    <label>propper message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/propper_message_date__c.field-meta.xml
<CustomField>
    <fullName>propper_message_date__c</fullName>
    <label>propper message date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AccountFieldCleanup.cls
public class AccountFieldCleanup implements Schedulable {
    public void execute(SchedulableContext context) {
        List<Account> accountsToUpdate = [SELECT Id, propper_message__c FROM Account WHERE propper_message__c != null AND propper_message_date__c < :Date.today().addDays(1)];
        for (Account acc : accountsToUpdate) {
            acc.propper_message__c = null;
        }
        update accountsToUpdate;
    }
}